### ISSUE TITLE
gluPaste not working

### ISSUE THREAD

**Issue by pranavk** [glugnith/glug.nith.ac.in#21]
gluPaste is not working. this needs to be taken care of as soon as possible.

@sagarkarira  is thinking of rewriting this in nodejs.

**Comment by divyanshu013** [comment]
@sagarkarira can you update the link on the website?

**Comment by sagarkarira** [comment]
@pranavk I rewrote it in nodejs :smile: long time back and  you can see it working [here](http://glug.nith.ac.in/paste) . Also I have updated the link on the website. @divyanshu013  But the issue with the the paste bin not loading correctly is because the paste bin server in running on node and on port 5000. So I have used ```ProxyPass /paste http://localhost:5000``` . Though the httpd server is redirecting me to this port but nothing is being loaded. Maybe @pranavk can help me out here.

**Comment by divyanshu013** [comment]
I'm sure he can.

**Comment by sagarkarira** [comment]
[Fixed](https://github.com/glugnith/glug.nith.ac.in/commit/655aa4f84f31400ac7c19c6f3f3d9f0b86be8883) Thanks to @binora
